### ISSUE TITLE
Chapter 4 Unable to Run 'runserver_plus'

### ISSUE THREAD

**Issue by Andyferguson** [PacktPublishing/Django-3-by-Example#108]
In Chapter 4, the section "Running the development server through 
HTTPS" I've followed the instructions closely however I get the following error:

```
`python manage.py runserver_plus --cert-file cert.crt
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django_extensions\management\utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django_extensions\management\commands\runserver_plus.py", line 262, in handle
    self.inner_run(options)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\django_extensions\management\commands\runserver_plus.py", line 339, in inner_run
    ssl_context = make_ssl_devcert(os.path.join(dir_path, root), host='localhost')
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 539, in make_ssl_devcert
    cert, pkey = generate_adhoc_ssl_pair(cn=cn)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\serving.py", line 498, in generate_adhoc_ssl_pair
    cert.gmtime_adj_notBefore(0)
  File "C:\Users\andyf\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenSSL\crypto.py", line 1349, in gmtime_adj_notBefore
    notBefore = _lib.X509_get_notBefore(self._x509)
AttributeError: module 'lib' has no attribute 'X509_get_notBefore'`
```

I can't find any open issues regarding this online.

I'm running Windows 10.

Can anyone help?
Thanks

**Comment by Andyferguson** [comment]
After a lot of searching on google I managed to sort the issue by uninstalling pyOpenSSL and reinstalling it with pip3 without stipulating a version.
