### ISSUE TITLE
Performing AJAX queries with jQuery

### ISSUE THREAD

**Issue by SPH73** [PacktPublishing/Django-3-by-Example#43]
I have 2 issues : 
If I split the template tag onto 2 lines then the endwith tag is seen as an error and the with tag is not recognised.
![image](https://user-images.githubusercontent.com/48051095/97586684-73c4f600-19f2-11eb-8a5b-f453560087d7.png)

Then next issue is when clicking on the like button on the image detail nothing happens; has anyone experienced the same? Are they related? 

EDIT
This is what i see in the network tab of the console
![image](https://user-images.githubusercontent.com/48051095/97589946-087d2300-19f6-11eb-87ef-e155ef843089.png)

so I will probably find the problem soon and will update.

Thanks in advance

```Traceback (most recent call last):
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 469, in parse
    compile_func = self.tags[command]
KeyError: 'endwith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/contrib/staticfiles/handlers.py", line 68, in __call__
    return self.application(environ, start_response)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sueholder/Desktop/code/bookmarks/src/images/views.py", line 36, in image_detail
    return render(request,
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 477, in parse
    raise self.error(token, e)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 475, in parse
    compiled_result = compile_func(self, token)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 471, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/sueholder/.local/share/virtualenvs/bookmarks-4AItjxlP/lib/python3.8/site-packages/django/template/base.py", line 521, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 40: 'endwith', expected 'endblock'. Did you forget to register or load this tag?```

**Comment by SPH73** [comment]
I can't find the what is causing the above and also the ajax request for pagination is also not working and not showing errors either; so if anyone can help me to figure out what I have not done or have done wrong or where I have gone wrong I would really appreciate it. I have gone as far as copying the code from the repo and still no joy. 
![image](https://user-images.githubusercontent.com/48051095/97836629-a01f9180-1cd4-11eb-9fac-1bd5bf1eb26d.png)
